version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE : school
      MYSQL_USER : admin
      MYSQL_ROOT : admin
      MYSQL_PASSWORD : admin
      MYSQL_ROOT_PASSWORD : root
    volumes:
      - ./storage/mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - 8080:80
    environment:
      MYSQL_USERNAME: "admin"
      MYSQL_ROOT_PASSWORD: "root"
      PMA_HOST: mysql
      UPLOAD_LIMIT: 300M
